name: list and Test

on: push

jobs:
    lint-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: action/checkout@v4
            
            - name: Setup Node
              uses: action/setup-node@v4
              with:
                node-version: '20'

            - name: Install Dependencies
              run: npm ci

            - name: Run Lint
              run: npm run lint

            - name: Run Test
              run: npm run test